export enum ContextKey {
  AcceptLanguage = "AcceptLanguage",
  RequestId = "RequestId",
  ServiceVersion = "ServiceVersion",
  UserAgent = "UserAgent",
  UserId = "UserId",
  RequestStartTime = "RequestStartTime",
  AppResponseCode = "AppResponseCode",
  DeviceType = "DeviceType",
  AppErrorMessage = "AppErrorMessage",
  CacheControl = "CacheControl",
  EventName = "EventName",
  EventDescription = "EventDescription",
  RequestBody = "RequestBody",
  RequestURI = "RequestURI",
  RequestMethod = "RequestMethod",
  RequestQuery = "RequestQuery",
  ClientIP = "ClientIP",
  ResponseHttpCode = "ResponseHttpCode",
  AuthToken = "AuthToken",
  ServiceName = "ServiceName",
  User = "User",
}
