version: '3'

services:
  # mongo:
  #     image: 'mongo:4.2.16-bionic'
  #     ports:
  #       - "27017:27017"
  #     environment:
  #       MONGO_INITDB_DATABASE: chat
  #       MONGO_INITDB_ROOT_USERNAME: admin
  #       MONGO_INITDB_ROOT_PASSWORD: password
  #     volumes:
  #       - ./db-data/mongo/:/data/db

  postgres:
    image: onjin/alpine-postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - "./db-data/postgres/scripts:/docker-entrypoint-initdb.d/"
      - "./db-data/postgres/data:/var/lib/postgresql/data"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp


  redis:
    image: redis:6
    restart: on-failure
    entrypoint:
      - "redis-server"
    volumes:
      - "./db-data/redis/conf:/usr/lib/redis/conf"
      - "./db-data/redis/modules:/usr/lib/redis/modules"
      - "./db-data/redis/data:/data"
    ports:
      - "6379:6379"